---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-app
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - image: zcrnivec/sample-app:test
        imagePullPolicy: Always
        name: sample-app

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-app
  name: sample-app
spec:
  ports:
  - nodePort: 32223
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: sample-app
  type: NodePort
